### ISSUE TITLE
Support for regex operators in Compass

### ISSUE THREAD

**Issue by desthomas1** [mongodb-js/compass#1887]
As of 23.01.2020, MongoDB Compass does not support $regexFindAll and $regexFind operators. Trying to use 'em within $addFields simply produced: 

> Expected "[" or AggregationStage but "{" found.

**Comment by lrlna** [comment]
Hi @desthomas1! Thanks for the report. I've added a [jira ticket](https://jira.mongodb.org/browse/COMPASS-4142) to track along with some of our other grammar fixes.

**Comment by Apodkaminnyy** [comment]
First of all, thanks for the great tool!
Right now, $regexMatch don't work as well, produces the same output in aggregation builder as $regexFindAll and $regexFind.
Maybe some sort of warning or notice about not supporting that operators is required, because current behavior can make people think that something is wrong with their query, when actually it is written well, and people can lose time while trying to find out what's wrong in the correct query.

**Comment by alenakhineika** [comment]
We fixed the issue and are closing the ticket. Feel free to reopen if you encounter any problems with that again.
