### ISSUE TITLE
Defect - Data import does not support nested structures anymore as of 1.21.0

### ISSUE THREAD

**Issue by HeberLZGlobant** [mongodb-js/compass#1949]
## Feature Request
Defect - Data import does not support nested structures anymore as of 1.21.0

## Detailed Description

Since the release of version 1.21.0, when importing data into a collection where the data for a field is a JSON, content for the field is treated as a string by default and none of the selectable field types seem to be for JSON-like objects. This was not an issue on version 1.20.5

Here is a screenshot of the newly released import flow and the different selectable field types, in my case the attribute is an array of strings
![image](https://user-images.githubusercontent.com/51335736/80751372-7fd10900-8ade-11ea-944d-97740280a9fa.png)

## Context

As it is working right now, importing an exported collection does not generate as output the same content. This is doable through CLI but it's something that was already supported and now it's not anymore

## Possible Implementation
>

**Comment by lrlna** [comment]
hi @HeberLZGlobant. Thanks for the report! This is definitely a bug. We will track it on the [JIRA ticket you already created](https://jira.mongodb.org/browse/COMPASS-4262)

**Comment by Anemy** [comment]
Hi @HeberLZGlobant - looks like this issue was fixed in the `1.22` release for JSON imports. Going to close this if that's alright, feel free to reopen if you update and it's not working as expected. Thanks again for reporting!
For a bit more context we are planning to improve the entire import/export experience in the coming months. (apologies for getting back late on github on this)
