### ISSUE TITLE
Feature Request: "Move to end" button in documents view

### ISSUE THREAD

**Issue by bluepuma77** [mongodb-js/compass#1976]
## Feature Request
Instead of just going back `<` and forward `>` in the documents view, it would be great to have a "move to the end" button `>>|` to see the latest documents. I personally have better things to do than click 1854 times on `>`.
<img width="773" alt="Mongo-move-to-end" src="https://user-images.githubusercontent.com/5221187/85799071-e8371200-b73e-11ea-8034-2363efd25a32.png">

## Detailed Description
Very easy, see summery above. Every single blog on the Internet has this "move to the end" button.

## Context
I would use it to see latest documents in my collection.

## Possible Implementation
Just put a `>>|` button in the GUI.
<img width="773" alt="Mongo-move-to-end2" src="https://user-images.githubusercontent.com/5221187/85799080-ec632f80-b73e-11ea-8a89-2e6374819f12.png">

**Comment by Anemy** [comment]
Thanks for the suggestion - and nice screenshot.
I'm a bit reluctant to add this in since it brings a bit more clutter to the UI and is something that a `sort` could probably address.
Does something like this work for your use case?
<img width="1056" alt="Screen Shot 2020-09-23 at 11 33 11 AM" src="https://user-images.githubusercontent.com/1791149/93994995-c32f5b00-fd90-11ea-9d28-faa81dda6cd7.png">

Going to close for now - it does look like something that's seen some activity on our feedback forum though, so maybe its worth upvoting there and we'll address it: https://feedback.mongodb.com/forums/924283-compass/suggestions/38666260-i-need-to-scan-and-page-through-query-results-quic (definitely showing more than 20 documents will be nice)

**Comment by rahbari** [comment]
this is a good feature. sort makes items reverse and every time it must be added. every db manager like navicat, intellij has this button.
