### ISSUE TITLE
Issue with SSH Tunnel and Identity File

### ISSUE THREAD

**Issue by duartegarin** [mongodb-js/compass#1985]
#### Current Behavior

I'm trying to connect to our Atlas clusters via compass.
We have whitelisted a bastion server and want to connect via SSH tunnel through the bastion.

The setup is the following:

Hostname: <primary cluster host>
Port: 27017
SRV record: False
Authentication: Username/pass
Auth db: admin

In more options:

Read preference: Primary (tried them all)
SSL: System CA
SSH Tunnel: Identity File
SSH hostname: The bastion host domain
SSH port: 22
SSH user name: <user>
Identity file: <id-file>

I get the message: "Hostname/IP does not match certificate's altnames: IP: 127.0.0.1 is not in the cert's list:"

If I try with unvalidated insecure, I get could not find config for 127.0.0.1

When I use Studio3T (trial) this works perfectly fine.

#### Environment

OSX
Tried both stable and beta2 version (both different error messages but same outcome)

#### Possible Solution

One thing I had to do with Studio3T is fill in a SNI record field and specify the primary cluster domain. Compass doesn't have this option.

Any ideas?
Thanks!

**Comment by Anemy** [comment]
Hi @duartegarin Currently we do not support using `System CA` SSL when connecting through SSH to a non-local connection. This is because we're attempting to validate the server's identity through the SSH tunnel, which will always be localhost/127.0.0.1, which cannot be validated to the server's hostname. Does setting SSL to `Unvalidated (insecure)` work for your connection and use case?

Thanks for reporting, sorry for any confusion, I think we can improve this UX to provide a better message in future.  Note: A few past compass versions worked when using `System CA` and SSH, but this was because of a bug which wasn't checking the server's hostname fully. Feel free to reopen this issue, there are some improvements we can do with SSH tunnels and TLS in future.
