### ISSUE TITLE
Bug Report - Saved password is exposable via developer tools

### ISSUE THREAD

**Issue by JafarAkhondali** [mongodb-js/compass#1997]
Not sure if this is the considered behavior or a security bug(concern).
In the connection window, password are saved but not visible to user. However, the password can be seen using DevTools.
#### Current Behavior
Currently, password can be seen using DevTools.

1. Open a new connection window
2. Use a saved connection with a password authentication or create a new connection 
2. Press `ctrl+alt+i` or Click on `View > Toggle dev tools`
3. Use inspect tool and select password field

![image](https://user-images.githubusercontent.com/11364402/90315357-26c39e80-df30-11ea-9a62-4e97ab4b9c44.png)

#### Expected Behavior/Code
I understand that you need the saved password to make the connection work, but if it's OK to let the user see it, there should a toggle button to let the user actually see it without using DevTools. This kind of data is sensitive and should not be exposed to user this easily. A local attacker might see the password fast and store it somewhere for further usages. 

#### Environment

- node.js / npm versions:  v12.18.2 /  6.14.5
- OS: Linux GNU\Debian 4.19.118-2

#### Possible Solution
It should be harder for end user to see the password.    
Some possible mitigations are:

- Use a master password for application usage and Encrypt saved password instead of showing the actual value in GUI, also ask for master password when want to see the
- Make password saving optional
- Disable DevTools

**Comment by Anemy** [comment]
Hi @JafarAkhondali - this is expected behavior. While we do encrypt passwords with the system's credential store, once Compass is open we want users to be able to customize their connections and as a result, view/change their password.

Your suggested solution around making password saving optional is definitely a solid idea. We've got that one in our feedback forum: https://feedback.mongodb.com/forums/924283-compass/suggestions/38666281-i-want-to-use-favorites-without-storing-passwords 
Maybe it's worth an upvote ;) 
Not planned when we'll work on it yet.

Thanks for bringing this up! Hope you're enjoying working with Compass & MongoDB.
