### ISSUE TITLE
Feature Request - Compass on Mac does not open new window on start

### ISSUE THREAD

**Issue by steffanhalv** [mongodb-js/compass#2014]
## Detailed Description

When opening compass on mac it does not create a window, I have to go in the menu bar in top and select `connect > connect to` before a window displays.

## Context

When I click the compass icon in doc, It is hard to see if compass has opened & if I use multiple monitors it is only visible in the menu bar on one of the multiple monitors.

## Possible Implementation

Execute `connect > connect to` by default when clicking the doc icon on mac if no windows is already open.

**Comment by Anemy** [comment]
@steffanhalv In the recent release https://github.com/mongodb-js/compass/releases/tag/v1.29.4 `1.29.4` we've added this feature so that Compass opens a new window when it's clicked in the dock and there are no open windows. Thanks to @gribnoysup for the fix!

Thanks for opening the issue! Feel free to reopen if you update and it doesn't work as expected.
