### ISSUE TITLE
MongoDB Atlas Cluster Database - can't login with X509 user with Compass (COMPASS-4544)

### ISSUE THREAD

**Issue by goldami1** [mongodb-js/compass#2085]
**Problem Description**
On version 1.22.1 it was still possible to connect with x509 (user) authentication to cluster db.
However, after upgrade to 1.24.1, it stopped to work.

**Steps to Reproduce**
1. Fill in connection fields individually
2. fill cluster dns name in Hostname field
3. SRV Record enabled
4. Authentication - X509, username: username as created in Atlas DB
5. Fill replica set name
6. Read Preference: Primary
7. SSL: Server and Client Validation
  7.1. Certificate Authority: PEM File from Mongo created for X509 User
  7.2. Client Certificate: PEM File from Mongo created for X509 User
  7.3. Client Private Key: PEM File from Mongo created for X509 User
8. Click CONNECT

**Expected Results**
Connects

**Actual Results**
"Auth failed" error

**Additional Notes**
Works perfectly on 1.22.1 Compass version, and on mongo cli.

**Comment by Anemy** [comment]
@goldami1 In 1.24.1 we updated our mongodb driver to 3.6.3 we had a fix where it started to use the username field supplied in the username field: https://github.com/mongodb/node-mongodb-native/commit/9110a45cfa9a536795fd3cbca92d1c1b4dc61d59 . Previously it seems this was unused. I suspect this is causing the issue. Sorry that updating caused it to stop working.

Two potential solutions:
- Remove the username value, we've now made it optional, and with the PEM from compass it is not needed as it is pulled from the CN field in the PEM.
- Update the username field to include `CN=` before the username so that it uses the username per [RFC-2253](https://tools.ietf.org/html/rfc2253). For example, the username "X509User" should be provided as "CN=X509User".

Thanks for creating the issue - hopefully one of those solutions fixes it for you. Feel free to re-open if that's not the case.
