### ISSUE TITLE
Mongosh exit command closes the connection

### ISSUE THREAD

**Issue by meryacine** [mongodb-js/compass#2127]
Running "exit" command in _MongoSH Beta spits out MongoshUnimplementedError : exit not supported for the current platform: Compass.
A simple disconnect and re-connect brings back the connection, but server refresh button beside the server icon causes "An error occurred while loading navigation: Topology is closed, please connect", have to re-open Compass for it to work.

**Comment by Anemy** [comment]
Hi @meryacine we're tracking this in https://jira.mongodb.org/browse/COMPASS-4585 we'll update here when it's fixed and live.  Thanks for bringing this up!

**Comment by Anemy** [comment]
Hi @meryacine sorry for the late reply, this is fixed in Compass - thanks again for reporting it!
<img width="1039" alt="Screen Shot 2022-02-08 at 3 23 02 PM" src="https://user-images.githubusercontent.com/1791149/153069412-7bf382a4-0e81-4181-a1bd-bc1a6b88ea2c.png">
For reference the release of Compass this fix landed in was 1.26.1
