### ISSUE TITLE
Windows 7 support for Compass 1.29.5

### ISSUE THREAD

**Issue by lorand-horvath** [mongodb-js/compass#2616]
First of all, I'd like to thank the MongoDB team behind the amazing piece of software that Compass proves to be!

I have noticed that the latest version of Compass 1.29 has Electron updated to v13 and Node.js to v14, reference:
https://github.com/mongodb-js/compass/releases/tag/v1.29.4

I am currently using the previous minor version 1.28.4 on Windows 7 x64 (which was built with an older version of Electron and Node.js 12).
Since Node.js 12 & 13 were the last versions to be officially supported on Windows 7, I would like to know if Compass 1.29.5, built on Node.js 14, is fully compatible with Windows 7 x64? If so, can I please ask how did you manage to achieve Node 14 compatibility with Windows 7? Perhaps I'm missing something, but I'm eager to find out & understand how it all fits together. Thanks!

**Comment by gribnoysup** [comment]
Hey @lorand-horvath, we're happy to hear that you seem to be enjoying using the Compass app!

The application itself is built on Electron, not Node.js and even though they both use the same v8 engine, they are not exactly the same runtimes. So even though Node.js doesn't support Windows 7 anymore, Electron does support [Windows 7](https://www.electronjs.org/docs/latest/tutorial/support#windows).

I'm totally not an expert here, but my understanding is that the main reason Node.js stopped supporting Windows 7 is `libuv` version update. Electron comes with a different version of `libuv` (seems to be the last one that supports Windows 7) and because of that is probably not affected by the deprecation

**Comment by lorand-horvath** [comment]
@gribnoysup Thanks for the detailed explanation, it was confusing to see Node 14 mentioned in the Compass 1.29 release notes, alongside the new Electron 13 version update. Node 14 won't install on Windows 7 by default, though there are solutions to force it...

**Comment by lorand-horvath** [comment]
Upgraded 1.28.4 to 1.29.5 without issues on Win 7 x64, seems to be working faster... though Windows Firewall asks permissions for some new service related to MongoDB Compass... very strange.
