### ISSUE TITLE
Incorrect amount of documents (and potentially storage size) shown for archive collections

### ISSUE THREAD

**Issue by philstussak** [mongodb-js/compass#2748]
Hi all,

When using Compass to show statistics about my Atlas Online Archive, the amount of documents shown does not match the amount of documents retuned by `db.collection.countDocuments()`. Also as seen below, storage amount also seems to be inconsistent (but I can't really prove this).

### Setup
- MongoDB Atlas Cluster (Mongodb version 4.4.12, Cluster Tier M60) with activated online archive for ~10 collections
- Archiving is running without errors or other issues
- Cluster data storage size at around 3.5TB, about 80% of the overall data is archived using a timestamp contained in each document. The remaining 20% are kept in hot access in the cluster.
- MongoDB Compass running on macOS Monterey 12.1, Compass version 1.30.1

### Issue and reproduction
- Connect to online archive using connection string from MongoDB Atlas 
<img width="1148" alt="Screenshot 2022-02-02 at 10 57 28" src="https://user-images.githubusercontent.com/7323922/152132396-f33e07a3-4109-49cc-87f6-5cb780540fdf.png">
- In Compass, database shows Storage Size of 2.33TB
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/7323922/152132654-2d5ad06c-4cf9-4045-802c-0120bdf62289.png">
- The collection overview shows much less (adding up all collection's storage size)
<img width="1018" alt="Screenshot 2022-02-02 at 11 03 50" src="https://user-images.githubusercontent.com/7323922/152133379-438d2e5a-8612-4233-9cba-a477b409b9f8.png">
- As seen in the screenshot above the first collection shows 2million documents, this is a rough estimate I guess but far from the amount of documents shown when running `db.dp_sensordata_5a0ed6891ccbf3000e8e60a3.countDocuments()` (~200million)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/7323922/152133864-4c8a994d-620f-475a-86ea-701ba0ba04cf.png">
- This applies to all collections in the archive (around factor 100 less documents shown)

### Things I tried:
- Restarting compass several times, restarting OS, reconnecting to archive several times. One time, I managed to see the "correct" storage and document amount after a few restarts of compass but I wasn't able to reproduce this since then.
- Retrieve new connection string from Atlas
- Refresh button in compass

Thanks for looking into it
-- Philipp

**Comment by Anemy** [comment]
Hi Philiipp, 
What's happening here is that Online Achive caches responses to `collStats`. Compass uses `collStats` to show the estimated document count and storage size you're seeing on the collections page. So this behavior is expected since the TTL of the cache is 7 days.
If you'd like to fetch the `collStats` information and bypass the cache you can append the `sync: true` option to the function call in mongosh. Doing this can have fairly significant costs - (it ends up doing a full coll scan of the data lake, which can rack up AWS fees depending on the structure).
I'm leaving this open for now - we're currently chatting with the team if we want to show some more information here to users to inform them of this behavior when connected to Atlas Online Archive, and maybe even show actions around refreshing the cache.

Thanks for using Compass and opening up the issue!

**Comment by philstussak** [comment]
Thanks for your response! Using `collStats` with `sync: true` is working perfectly, thanks for the hint on that. Feel free to close this issue whenever you want - from my side its fine :)

**Comment by Anemy** [comment]
Thanks - a ticket was opened up on this in jira so we can track it there: https://jira.mongodb.org/browse/COMPASS-5353
