### ISSUE TITLE
An error occurred while rendering ConnectedDocumentList: Argument passed in UUID constructor must be a UUID, a 16 byte Buffer or a 32/36 character hex string (dashes excluded/included, format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

### ISSUE THREAD

**Issue by miso419** [mongodb-js/compass#2974]
#### Current Behavior
With the latest Compass 1.31.1, it always throws `An error occurred while rendering ConnectedDocumentList: Argument passed in UUID constructor must be a UUID, a 16 byte Buffer or a 32/36 character hex string (dashes excluded/included, format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)` on any tabs (Documents, Aggregations, etc.). It worked with 1.28.x.
<img width="1250" alt="Screen Shot 2022-04-12 at 2 53 49 pm" src="https://user-images.githubusercontent.com/8870129/162890382-339340f8-956d-4505-ba0d-1794252c31b5.png">

#### Environment
OS: macOS Monterey ver 12.3.1

**Comment by gribnoysup** [comment]
Hi @miso419, thanks for reporting the issue! Does it happen when you open a particular collection? Can you share UUID of some documents so we can try and reproduce the problem?

**Comment by Anemy** [comment]
I think this is due to previous versions of Compass more gracefully handling binary data that has the UUID type but doesn't match the proper format: https://www.mongodb.com/docs/manual/reference/mongodb-extended-json/#mongodb-bsontype-Binary  
As UUIDs can exist in the database in a format that the `bson` package throws an error parsing I think we probably want to be a bit more permissive here and allow displaying these documents. Probably one of the recent changes made this a bit more strict - sorry! @miso419 you might want to ensure your documents all have UUIDs in the correct format, as that would probably fix this issue from occurring. 
Thanks for reporting this. Here's a jira issue to track: https://jira.mongodb.org/browse/COMPASS-5726
We'll post back here when there's an update/fix out.
