### ISSUE TITLE
Feature Request: Better Dark Theme

### ISSUE THREAD

**Issue by AmitKumarHQ** [mongodb-js/compass#3180]
## Feature Request
I would like to request for a **Minimal and Clean Dark Theme**, as the current theme isn't too good in my opinion.

## Detailed Description
The current dark theme is only the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) extension with the default light theme.  

## Context
Add a Preference tab, where we can customize the appearance and also add a more contrast and clean, dark theme, with much more customizability and proper visibility of the elements. The current **Performance Tab** is extremely difficult to view in dark mode. 
![image](https://user-images.githubusercontent.com/94821119/173195299-b4d364a5-b68a-4317-b7ac-23cda3443af4.png)

**Comment by Anemy** [comment]
Hi @AmitKumarHQ, thanks for opening the issue. Improving dark mode is something we're currently tracking in our feedback forum: https://feedback.mongodb.com/forums/924283-compass/suggestions/38666287-i-would-like-a-dark-theme
The current dark mode is a preview of things to come. Some additional context, we're currently in the process of updating all of our components to support a dark mode with better contrast and more inline with MongoDB's design: https://www.mongodb.design/
I'm going to close this ticket since we're tracking it already. Feel free to reopen.
