### ISSUE TITLE
Bug Report: Exported golang pipeline bson.D pipeline should used keyed fields

### ISSUE THREAD

**Issue by alexanderpalsson** [mongodb-js/compass#3183]
## Bug Report
Currently, the exporter uses unkeyed fields for bson.D.

#### Current Behavior
`  bson.D{{"key", "val"}}
` 

#### Expected Behavior/Code
`  bson.D{{Key: "key", Value: "val"}}
`

#### Environment

- node.js / npm versions:
- OS:

**Comment by gribnoysup** [comment]
Hi @alexanderpalsson! Thanks for opening an issue. Although both the current and the expected syntax that you provided in the description are valid, we made an intentional decision to implement the current behavior so that the generated code is aligned with the [go driver documentation](https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo)

**Comment by alexanderpalsson** [comment]
@gribnoysup understandable even though it is against go recommendations `We therefore recommend that composite literals whose type is defined in a separate package should use the keyed notation.` https://go.dev/doc/go1compat#expectations
