### ISSUE TITLE
Compass does not save favorites on WSL

### ISSUE THREAD

**Issue by l0ner** [mongodb-js/compass#3512]
Just as in title. I have Compass installed in WSL. I can add as many favories as I can, but if I close Compass and reopen it all the favorites are gone.

From reading #1911 and #1956 it might seem the gnome-keyring is needed for this to function, and some users have resolved this simply by installing it. I do have gnome-keyring installed and autostarting in my WSL installation, and applications like Remmina use it without a problem.

#### Current Behavior

Favorites do not persist Compass restart on WSL

#### Expected Behavior/Code

Favorites persist every Compass restart.

#### Environment

- node.js / npm versions: v16.17.0 / 8.1.3
- OS: Ubuntu 20.04.5 on Windows 11 WSL2
- Compass: 1.32.2 && 1.26.0

### Steps to reproduce

1. Install Mongodb Compass on WSL
2. Open Compass
3. Add some Favorites
4. Close Compass
5. Reopen Compass, favorites are gone.

**Comment by alenakhineika** [comment]
Hey, thank you for opening the issue! We have a ticket open that might be related to what causes this ([COMPASS-6119](https://jira.mongodb.org/browse/COMPASS-6119)). You can use it as a reference to track the progress.

**Comment by l0ner** [comment]
Thanks for the update. Since last(?) update i can now enable systemd on WSL, which made the problem go away. I guess the problem lies with some service (dbus? keychanin?) which is required for bookmarks to work but is not started on WSL that doesn't run systemd.

**Comment by Anemy** [comment]
Closing this, we're planning to add a warning for folks that run into this issue here: https://jira.mongodb.org/browse/COMPASS-7819 
We're also investigating some additional fallbacks for when folks can't access credential storage. In some more recent versions we've made it so that when credential storage can't be accessed favorites can still be saved, they just don't retain password like things.
