### ISSUE TITLE
Feature Request: Color Picker on Favorite save

### ISSUE THREAD

**Issue by bozzelliandrea** [mongodb-js/compass#3963]
#### Proposal
Add a color picker in the favorites save modal.

**Comment by Anemy** [comment]
Hi @bozzelliandrea thanks for the feature request and idea - it is something we considered when rebuilding the connection form recently and we decided at the time to limit the colors to make sure things looked nice across the app wherever we use the favorite color.

We've moved our feature requests to the feedback forum as they're easier to track there and we'd like to prioritize bugs and issues on GitHub. You can find the feedback forum here: https://feedback.mongodb.com/forums/924283-compass
I'm going to close this issue if that's alright, as we don't use GitHub for feature requests.

On a quick search it does look like someone has requested this before: https://feedback.mongodb.com/forums/924283-compass/suggestions/41871448-allow-custom-colors-of-favorites If you'd like to you can upvote it so it can be better prioritized.

**Comment by bozzelliandrea** [comment]
Hi @Anemy thanks for the feedback 😄, but I have a question, is it possible to implement this feature or contribute?  are the issues only in the forum and need to be upvoted before implementing them?

**Comment by Anemy** [comment]
@bozzelliandrea We do accept contributions from folks. The feedback forum is mostly for us to get a sense of what people want added or changed in the app so that we can plan larger projects. For a pull request to be accepted we'll typically look for tests and you'll have to sign the contributors agreement: https://www.mongodb.com/legal/contributor-agreement 

Here's where the color picker is: https://github.com/mongodb-js/compass/blob/main/packages/connection-form/src/components/favorite-color-picker.tsx
It might need some backend work updating where the color is saved, as well as some considerations for background and text color contrast where the color is used. Please also keep in mind the design team might have had some reasons for not wanting to allow folks to choose any color for their favorite, I think an outside pull request would help persuade the team that it could be useful.

Thanks for the interest!
